---
title: "Readme"
author: "Lisa Leung"
date: '2018-04-02'
output: github_document
---

## a-clust

-This file includes the source code for the A-clust package, in addition, to source codes written by us to use the package in a convenient way for our application.

## Step1.md and Step1.Rmd
In this file, we explain the process of organizing data into an R-friendly format and extracting the essential part of data from the ROSMAP dataset. We then go through the multicollinearity issue in our CpG probes and how we correct it. We then assess the outliers in gene expression and methylation data.
## project_data_description.Rmd and project_data_description.md

- These files provides a detailed description of the raw data set we have obtained for our project. It describes the ROSMAP data sets.

## Step1_files (Images Folder)

- Step_files will include all the images that are produced in Markdown file

## Data

### ROSMAP Data

- We used the ROSMAP raw data published by [synapse](https://www.synapse.org/) as the input to this step. Due to the confidentiality issues, interested scientists can directly contact synapse for downloading the data using the link below:

https://www.synapse.org/#!Synapse:syn3219045


### rosmap_postprocV2.RData

- The data sets produced here consists of the results from Step 1. The .RData folder consists of three data sets: probes_subjects, subjects_genes, and probes_genes_distance. The probes_subjects data consists of DNA methylation probe data, subjects_genes consists of gene expression values, and probes_genes_distance consists of the distances on probes and genes where 0 represents a distance over 1Mb. Since it is too large to be uploaded in github, the data set could be found in this Google Drive Folder:

https://drive.google.com/drive/folders/1u7J2reJVtPl2IVVytpTqWqJm-76lu0OY?usp=sharing
